### PR TITLE
clarify about concurrency / safety

### PR DESCRIPTION
**Pull request by bensigelman**

### CODE REVIEW

**Comment by bensigelman** [comment]
Per #11.

**Comment by yurishkuro** [comment]
LGTM. 

@slimsag did you want to see anything else?

**Comment by slimsag** [comment]
LGTM.

We will also want to have this be a part of the Go package docs at (https://godoc.org/github.com/opentracing/api-golang/opentracing) but this can be done as a follow-up. I'll see if I can send a PR for this tomorrow.

**Comment by bensigelman** [comment]
@slimsag makes sense re the godocs. We need a package-level comment there; hopefully it can point to the main `opentracing.github.io` site for general background.

**Pull request merged**
